### ISSUE TITLE
Ability to install via Findbugs Maven plugin

### ISSUE THREAD

**Issue by tomfitzhenry** [tomfitzhenry/findbugs-guice#10]
See http://jira.codehaus.org/browse/MFINDBUGS-151

**Comment by ThrawnCA** [comment]
This has long since been resolved, and the plugin can now be used as:

    <plugin>
        <groupId>org.codehaus.mojo</groupId>
        <artifactId>findbugs-maven-plugin</artifactId>
        <version>3.0.1</version>
        <configuration>
            <plugins>
                <plugin>
                    <groupId>uk.me.tom-fitzhenry.findbugs-guice</groupId>
                    <artifactId>findbugs-guice</artifactId>
                    <version>0.5</version>
                </plugin>
            </plugins>
        </configuration>
    </plugin>

**Comment by tomfitzhenry** [comment]
Thanks for telling me this. I don't have the means to easily test this at the moment, but will once I get chance.
On 19 May 2015 12:27 pm, ThrawnCA <notifications@github.com> wrote:This has long since been resolved, and the plugin can now be used as:

<plugin>
    <groupId>org.codehaus.mojo</groupId>
    <artifactId>findbugs-maven-plugin</artifactId>
    <version>3.0.1</version>
    <configuration>
        <plugins>
            <plugin>
                <groupId>uk.me.tom-fitzhenry.findbugs-guice</groupId>
                <artifactId>findbugs-guice</artifactId>
                <version>0.5</version>
            </plugin>
        </plugins>
    </configuration>
</plugin>

**Comment by tomfitzhenry** [comment]
Thanks. This indeed did work!
